# Generated by Django 4.2.6 on 2023-11-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_tlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tlist',
            name='completion_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
